name: Report
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: Report
        uses: dorny/test-reporter@v1.4.2
        with:
          artifact: TestResults-${{ inputs.name }}
          name: Test Results
          path: "*.trx"
          reporter: dotnet-trx
